
package com.oracle.xmlns.adf.svc.errors;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12.redhat-1
 * 2018-07-27T11:37:11.477+08:00
 * Generated source version: 3.1.12.redhat-1
 */

@WebFault(name = "ServiceErrorMessage", targetNamespace = "http://xmlns.oracle.com/adf/svc/errors/")
public class ServiceException extends Exception {
    
    private com.oracle.xmlns.adf.svc.errors.ServiceErrorMessage serviceErrorMessage;

    public ServiceException() {
        super();
    }
    
    public ServiceException(String message) {
        super(message);
    }
    
    public ServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceException(String message, com.oracle.xmlns.adf.svc.errors.ServiceErrorMessage serviceErrorMessage) {
        super(message);
        this.serviceErrorMessage = serviceErrorMessage;
    }

    public ServiceException(String message, com.oracle.xmlns.adf.svc.errors.ServiceErrorMessage serviceErrorMessage, Throwable cause) {
        super(message, cause);
        this.serviceErrorMessage = serviceErrorMessage;
    }

    public com.oracle.xmlns.adf.svc.errors.ServiceErrorMessage getFaultInfo() {
        return this.serviceErrorMessage;
    }
}
