
package com.emc.drcap.nemsprerequisite;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ControllerRunFault", targetNamespace = "http://nemsprerequisite.drcap.emc.com/")
public class ControllerRunFault
    extends Exception implements java.io.Serializable
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NmesFaulttBean faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ControllerRunFault(String message, NmesFaulttBean faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ControllerRunFault(String message, NmesFaulttBean faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.emc.drcap.nemsprerequisite.NmesFaulttBean
     */
    public NmesFaulttBean getFaultInfo() {
        return faultInfo;
    }

}
