package com.emc.rex.model.bc.am.common;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12.redhat-1
 * 2018-10-31T18:18:12.779+08:00
 * Generated source version: 3.1.12.redhat-1
 * 
 */
@WebService(targetNamespace = "/com/emc/rex/model/bc/am/common/", name = "RexInternalService")
@XmlSeeAlso({sdo.commonj.java.ObjectFactory.class, com.emc.rex.model.bc.am.common.types.ObjectFactory.class, sdo.commonj.ObjectFactory.class, com.oracle.xmlns.adf.svc.errors.ObjectFactory.class})
public interface RexInternalService {

    @WebMethod(action = "/com/emc/rex/model/bc/am/common/startREXRunByRunDate")
    @RequestWrapper(localName = "startREXRunByRunDate", targetNamespace = "/com/emc/rex/model/bc/am/common/types/", className = "com.emc.rex.model.bc.am.common.types.StartREXRunByRunDate")
    @ResponseWrapper(localName = "startREXRunByRunDateResponse", targetNamespace = "/com/emc/rex/model/bc/am/common/types/", className = "com.emc.rex.model.bc.am.common.types.StartREXRunByRunDateResponse")
    @WebResult(name = "result", targetNamespace = "/com/emc/rex/model/bc/am/common/types/")
    public java.lang.String startREXRunByRunDate(
        @WebParam(name = "RunDate", targetNamespace = "/com/emc/rex/model/bc/am/common/types/")
        java.lang.String runDate,
        @WebParam(name = "comments", targetNamespace = "/com/emc/rex/model/bc/am/common/types/")
        java.lang.String comments,
        @WebParam(name = "runType", targetNamespace = "/com/emc/rex/model/bc/am/common/types/")
        java.lang.String runType,
        @WebParam(name = "userId", targetNamespace = "/com/emc/rex/model/bc/am/common/types/")
        java.lang.String userId
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "/com/emc/rex/model/bc/am/common/getPDFBytes")
    @RequestWrapper(localName = "getPDFBytes", targetNamespace = "/com/emc/rex/model/bc/am/common/types/", className = "com.emc.rex.model.bc.am.common.types.GetPDFBytes")
    @ResponseWrapper(localName = "getPDFBytesResponse", targetNamespace = "/com/emc/rex/model/bc/am/common/types/", className = "com.emc.rex.model.bc.am.common.types.GetPDFBytesResponse")
    @WebResult(name = "result", targetNamespace = "/com/emc/rex/model/bc/am/common/types/")
    public byte[] getPDFBytes(
        @WebParam(name = "runDate", targetNamespace = "/com/emc/rex/model/bc/am/common/types/")
        java.lang.String runDate,
        @WebParam(name = "ptpId", targetNamespace = "/com/emc/rex/model/bc/am/common/types/")
        java.lang.String ptpId
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;

    @WebMethod(action = "/com/emc/rex/model/bc/am/common/startREXRunByTradingDate")
    @RequestWrapper(localName = "startREXRunByTradingDate", targetNamespace = "/com/emc/rex/model/bc/am/common/types/", className = "com.emc.rex.model.bc.am.common.types.StartREXRunByTradingDate")
    @ResponseWrapper(localName = "startREXRunByTradingDateResponse", targetNamespace = "/com/emc/rex/model/bc/am/common/types/", className = "com.emc.rex.model.bc.am.common.types.StartREXRunByTradingDateResponse")
    @WebResult(name = "result", targetNamespace = "/com/emc/rex/model/bc/am/common/types/")
    public java.lang.String startREXRunByTradingDate(
        @WebParam(name = "tradingDate", targetNamespace = "/com/emc/rex/model/bc/am/common/types/")
        java.lang.String tradingDate,
        @WebParam(name = "comments", targetNamespace = "/com/emc/rex/model/bc/am/common/types/")
        java.lang.String comments,
        @WebParam(name = "runType", targetNamespace = "/com/emc/rex/model/bc/am/common/types/")
        java.lang.String runType,
        @WebParam(name = "userId", targetNamespace = "/com/emc/rex/model/bc/am/common/types/")
        java.lang.String userId
    ) throws com.oracle.xmlns.adf.svc.errors.ServiceException;
}
